{% set name = "dandi" %}
{% set version = "0.39.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73f5d6d2b1cdcada683e823d666a01b485109c7e6b4d714bd91e1ef28daeb9c2

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - dandi=dandi.cli.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - appdirs
    - click
    - click-didyoumean
    - dandischema >=0.6.0,<0.7.0
    - etelemetry >=0.2.0
    - fasteners
    - fscacher
    - humanize
    - importlib-metadata
    - interleave
    - joblib
    - keyring
    - keyrings.alt
    - packaging
    - pycryptodomex
    - pydantic >=1.9.0
    - pynwb >=1.0.3,!=1.1.0
    - pyout >=0.5,!=0.6.0
    - python-dateutil
    - requests >=2.20,<3.0
    - ruamel.yaml >=0.15,<1
    - semantic_version
    - tenacity
    - zarr >=2.10,<3.0

test:
  requires:
    - anys
    - docker-compose  # [not win]
    - git
    - opencv
    - pytest
    - pytest-mock
    - responses
  imports:
    - dandi
  commands:
    - python -m pytest -s -v --pyargs dandi

about:
  home: https://github.com/dandi/dandi-cli
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command line client for interaction with DANDI Archive elements
  dev_url: https://github.com/dandi/dandi-cli

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
